- name: Docker Repo
  yum_repository:
    name: Docker
    description: docker-ce-stable
    file: docker-ce
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgcheck: 1
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: Install Docker
  yum:
    name: docker-ce
    state: present




